
FROM node:22-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Genereer Prisma Client
RUN npx prisma generate

EXPOSE 5000

CMD ["npm", "run", "dev"]